from fpdf import FPDF
from datetime import datetime
from app.services.currency_service import format_pdf_amount


def generate_invoice_pdf(invoice, user) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    currency = getattr(invoice, "currency", "USD") or "USD"

    # Header bar
    pdf.set_fill_color(67, 56, 202)
    pdf.rect(0, 0, 210, 48, "F")

    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(15, 10)
    pdf.cell(100, 12, "FinanceAPI", ln=False)

    pdf.set_font("Helvetica", "B", 13)
    pdf.set_xy(140, 10)
    pdf.cell(55, 12, "INVOICE", align="R", ln=False)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_xy(140, 24)
    pdf.cell(55, 8, f"# {str(invoice.id).zfill(6)}", align="R", ln=True)

    pdf.set_text_color(30, 30, 30)

    # Invoice meta + bill to
    pdf.set_xy(15, 58)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(90, 7, "Invoice Details", ln=False)
    pdf.cell(90, 7, "Bill To", ln=True)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_x(15)
    pdf.cell(90, 7, f"Invoice #:  {str(invoice.id).zfill(6)}", ln=False)
    pdf.cell(90, 7, invoice.customer_name, ln=True)

    pdf.set_x(15)
    pdf.cell(90, 7, f"Date:  {invoice.created_at.strftime('%B %d, %Y')}", ln=False)
    pdf.cell(90, 7, invoice.customer_email or "", ln=True)

    status_label = (getattr(invoice, "status", "pending") or "pending").upper()
    pdf.set_x(15)
    pdf.cell(90, 7, f"Status:  {status_label}", ln=False)
    pdf.cell(90, 7, f"Currency:  {currency}", ln=True)

    pdf.ln(12)

    # Table header
    pdf.set_fill_color(237, 238, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_x(15)
    pdf.cell(130, 10, "Description", border=1, fill=True, ln=False)
    pdf.cell(55, 10, "Amount", border=1, fill=True, align="R", ln=True)

    # Rows
    pdf.set_font("Helvetica", "", 10)
    pdf.set_x(15)
    pdf.cell(130, 9, "Subtotal", border=1, ln=False)
    pdf.cell(55, 9, format_pdf_amount(invoice.amount, currency), border=1, align="R", ln=True)

    tax_amount = invoice.amount * invoice.tax / 100
    pdf.set_x(15)
    pdf.cell(130, 9, f"Tax ({invoice.tax}%)", border=1, ln=False)
    pdf.cell(55, 9, format_pdf_amount(tax_amount, currency), border=1, align="R", ln=True)

    # Total row
    pdf.set_fill_color(67, 56, 202)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_x(15)
    pdf.cell(130, 12, "TOTAL", border=1, fill=True, ln=False)
    pdf.cell(55, 12, format_pdf_amount(invoice.total, currency), border=1, fill=True, align="R", ln=True)

    # Footer
    pdf.set_text_color(150, 150, 150)
    pdf.set_font("Helvetica", "I", 9)
    pdf.ln(18)
    pdf.set_x(15)
    pdf.cell(0, 8, "Thank you for your business!", align="C", ln=True)
    pdf.set_x(15)
    pdf.cell(0, 7, f"Generated by FinanceAPI  |  {datetime.utcnow().strftime('%B %d, %Y')}", align="C")

    return bytes(pdf.output())
